/** Public surface of the pure domain engine (Phase 1). */
export * from "./model";
export * from "./fields";
export * from "./scope";
export * from "./columns/operators";
export * from "./columns/column-type";
export * from "./columns/registry";
export * from "./columns/index";
export * from "./columns/infer";
export * from "./extract/extractor";
export * from "./extract/combine";
export * from "./extract/markdown-table";
export * from "./extract/table-extractor";
export * from "./extract/frontmatter-extractor";
export * from "./extract/task-extractor";
export * from "./extract/inline-field-extractor";
export * from "./query/index";
export * from "./transform/index";
export * from "./annotations/index";
